Repository s1mark/cloud, pull requests merged in 2022-11, with the labels that each got.

#82 Added files to VM
  Utassy Denes - FQ4AC3/module/VM/main.tf
  Utassy Denes - FQ4AC3/module/VM/providers.tf
  Utassy Denes - FQ4AC3/module/VM/variables.tf
  _core/monday/VM/main.tf
Labels: completed

#70 Szabó Gergő - added gcp vm
  YGJWWN/module/vm/main.tf
  YGJWWN/module/vm/provider.tf
  YGJWWN/module/vm/variables.tf
  _core/thursday/vm/main.tf
Labels: invalid

#72 Lgp zh5 ed7
  ZH5ED7-LGP/.terraform.lock.hcl
  ZH5ED7-LGP/ASD.txt
  ZH5ED7-LGP/cloudd.tf
  ZH5ED7-LGP/main.tf
  ZH5ED7-LGP/modul/vm/main.tf
  ZH5ED7-LGP/modul/vm/provider.tf
  ZH5ED7-LGP/modul/vm/variables.tf
  ZH5ED7-LGP/provider.tf
  ZH5ED7-LGP/test.tf
  ZH5ED7-LGP/valami.txt
  ZH5ED7-LGP/variables.tf
  _core/thursday/vm/main.tf
Labels: missing

#79 created gcp vm
  Kiss Dorina Hedvig - BSX8GS/module/vm/main.tf
  Kiss Dorina Hedvig - BSX8GS/module/vm/provider.tf
  Kiss Dorina Hedvig - BSX8GS/module/vm/variables.tf
Labels: missing

#80 CAZJQD
  CAZJQD/module/vm/main.tf
  CAZJQD/module/vm/provider.tf
  CAZJQD/module/vm/variables.tf
  _core/thursday/vm/main.tf
Labels: missing

#89 EENUGW
  EENUGW/VM/.terraform.lock.hcl
  EENUGW/VM/main.tf
  EENUGW/VM/provider.tf
  EENUGW/examples/.terraform.lock.hcl
  EENUGW/examples/first
  EENUGW/examples/outputs.tf
  EENUGW/examples/provider.tf
  EENUGW/examples/run.tf
  EENUGW/examples/second
  EENUGW/examples/service.tf
  EENUGW/examples/third
  EENUGW/examples/variables.tf
  EENUGW/module/VM/main.tf
  EENUGW/module/VM/provider.tf
  EENUGW/module/VM/variables.tf
  _core/monday/VM/main.tf
Labels: invalid

#87 Wgxnp2
  Bagoly Gábor - OOHQ3E/11_14/module/vm/compute_instance/variables.tf
  WGXNP2/module/VM/.terraform.lock.hcl
  WGXNP2/module/VM/main.tf
  WGXNP2/module/VM/provider.tf
  WGXNP2/module/VM/variables.tf
  WGXNP2/module/api/main.tf
  WGXNP2/module/api/outputs.tf
  WGXNP2/module/api/provider.tf
  WGXNP2/module/api/variables.tf
  _core/monday/VM/main.tf
Labels: invalid

#74 Jhpipm
  .gitignore
  JHPIPM/modul/vm/main.tf
  JHPIPM/modul/vm/provider.tf
  JHPIPM/modul/vm/variables.tf
Labels: missing
